// Generated by CoffeeScript 1.7.1
(function() {
  var greeting, isGoint, job, mulit, name, noMulit, num, number, obj, one, range1, range2, range3, three, two, _ref;

  name = 'Rafal';

  greeting = "Hello, " + name + "!";

  noMulit = " some content some more here and one more line here";

  mulit = "\nThis is a greeting\n\n    " + greeting + "\n";

  number = 13.15;

  isGoint = true;

  isGoint = true;

  isGoint = true;

  range1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  range2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  range3 = [20, 19, 18, 17, 16, 15, 14, 13, 12, 11];

  obj = {
    name: 'Rafal',
    job: 'Programmer'
  };

  name = 'Rafal';

  job = 'Programmer';

  obj = {
    name: name,
    job: job
  };

  _ref = [1, 2, 3], one = _ref[0], two = _ref[1], three = _ref[2];

  obj = {
    name: name,
    job: "Programmer",
    other: {
      name: name
    }
  };

  num = 10;

  console.log(num + 1);

}).call(this);
