// Generated by CoffeeScript 1.7.1

/*
alias:
is  -> ===
isnt -> !==
 */

(function() {
  var job, name, name1, name2, person, x, _ref, _ref1;

  name = "Rafal";

  if (name === "Rafal") {
    console.log("Hi");
  }

  if (name !== "Rafal") {
    console.log("Hi");
  }


  /*
      if (! false) {
  
      }
       not
   */

  if (!false) {
    console.log("Hi");
  }


  /*
  
      var name = "Rafal",
          job = "Programmer"
  
      if( name === 'Rafal' || job === 'Programmer' ) {
          console.log( 'Hi!');
      }
   */

  name = "Rafal";

  job = "Programmer";

  if (name === "Rafal" && job === "Programmer") {
    console.log("Hi!");
  }

  if (name === "Rafal" || job === "Programmer") {
    console.log("Hi!");
  }

  name = "Rafal";

  if (name != null) {
    console.log("Hi!");
  }

  person = {
    name: "Rafal",
    job: "Programmer"
  };

  console.log(person != null ? person.name : void 0);

  console.log(person != null ? (_ref = person.name) != null ? (_ref1 = _ref.firstLetter) != null ? _ref1.somethingelese : void 0 : void 0 : void 0);

  name = "Rafal";

  name || (name = "Rafal");

  if (name == null) {
    name = "Rafal";
  }

  name1 = "Rafal";

  name2 = name1 || "Joe";

  console.log(name2);

  x = 4;

  if ((0 <= x && x <= 10)) {
    console.log("Hi");
  }

}).call(this);
