// Generated by CoffeeScript 1.7.1
(function() {
  var classroom, courseTopic, root;

  courseTopic = 'CoffeeScript';

  console.log(courseTopic);

  console.log(this.courseTopic);

  console.log(window.courseTopic);

  this.courseTopic = courseTopic;

  console.log(courseTopic);

  console.log(this.courseTopic);

  console.log(window.courseTopic);

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.courseTopic = courseTopic;

  console.log(courseTopic);

  console.log(this.courseTopic);

  console.log(window.courseTopic);

  classroom = {
    students: ["John", "Jane", "Jill", "Joe"],
    print: function() {
      var getName, i, s, _i, _len, _ref, _results;
      getName = (function(_this) {
        return function(i) {
          return _this.students[i];
        };
      })(this);
      _ref = this.students;
      _results = [];
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        s = _ref[i];
        _results.push(console.log(getName(i)));
      }
      return _results;
    }
  };

  classroom.print();

}).call(this);
