<?php
require 'Calculator.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-25 at 13:02:00.
 */
class CalculatorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Calculator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Calculator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert (1,3) == 4.
     *
     * @covers Calculator::add
     */
    public function testAdd()
    {
        $this->assertEquals(
          4
,
          $this->object->add(1,3)
        );
    }

    /**
     * Generated from @assert (7,3) == 4.
     *
     * @covers Calculator::sub
     */
    public function testSub()
    {
        $this->assertEquals(
          4
,
          $this->object->sub(7,3)
        );
    }

    /**
     * @covers Calculator::multiply
     * @todo   Implement testMultiply().
     */
    public function testMultiply()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Calculator::divide
     * @todo   Implement testDivide().
     */
    public function testDivide()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
