// Generated by CoffeeScript 1.7.1
(function() {
  var Site, arr, i, key, obj, siteName, value, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _m, _n,
    __hasProp = {}.hasOwnProperty;

  arr = ['Nettus+', 'Aetuts', 'Phototuts+'];


  /*
      for( var i = 0; i < arr.length, i ++) {
          console.log(arr[i])
      }
   */

  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    siteName = arr[_i];
    console.log(siteName);
  }

  for (i = _j = 0, _len1 = arr.length; _j < _len1; i = ++_j) {
    siteName = arr[i];
    console.log("" + i + ": " + siteName);
  }

  for (i = _k = 0, _len2 = arr.length; _k < _len2; i = ++_k) {
    siteName = arr[i];
    if (siteName.indexOf("P") === 0) {
      console.log("" + i + ": " + siteName);
    }
  }

  for (i = _l = 0, _len3 = arr.length; _l < _len3; i = _l += 2) {
    siteName = arr[i];
    console.log("" + i + ": " + siteName);
  }

  for (i = _m = 0, _len4 = arr.length; _m < _len4; i = ++_m) {
    siteName = arr[i];
    if (1 % 2 === 0) {
      console.log("" + i + ": " + siteName);
    }
  }

  for (_n = 0, _len5 = arr.length; _n < _len5; _n++) {
    siteName = arr[_n];
    console.log(siteName);
  }

  console.log((function() {
    var _len6, _o, _results;
    _results = [];
    for (_o = 0, _len6 = arr.length; _o < _len6; _o++) {
      siteName = arr[_o];
      _results.push(siteName);
    }
    return _results;
  })());

  console.log((function() {
    var _len6, _o, _results;
    _results = [];
    for (_o = 0, _len6 = arr.length; _o < _len6; _o++) {
      siteName = arr[_o];
      _results.push(siteName.length);
    }
    return _results;
  })());

  for (key in obj) {
    value = obj[key];
    console.log("" + key + ":, " + value);
  }

  for (key in obj) {
    value = obj[key];
    if (key !== "name") {
      console.log("" + key + ":, " + value);
    }
  }


  /*
  for (val in obj) {
    if (obj.hasOwnPropety(val))  {
  
    }
  }
   */

  obj = {
    name: 'Nettuts+',
    topic: 'Web Development',
    editor: 'Jeffrey Way'
  };

  for (key in obj) {
    if (!__hasProp.call(obj, key)) continue;
    value = obj[key];
    console.log("" + key + ":, " + value);
  }

  Site = function(name) {
    return this.name = name;
  };

  Site.prototype.topic = "Web Developent";

  for (key in obj) {
    if (!__hasProp.call(obj, key)) continue;
    value = obj[key];
    console.log("" + key + ":, " + value);
  }

  i = 0;

  while (arr[i]) {
    console.log(arr[i]);
    i++;
  }

  i = 0;

  while (!(i === arr.length)) {
    console.log(arr[i]);
    i++;
  }

  i = 0;

  while (i !== arr.length) {
    console.log(arr[i]);
    i++;
  }

  i = 0;

  while (i !== arr.length) {
    console.log(arr[i++]);
  }

  while (true) {
    console.log(arr[i++]);
    if (!(i < arr.length)) {
      break;
    }
  }

}).call(this);
