// Generated by CoffeeScript 1.7.1

/*

function greet(name) {
    console.log( 'hello ' + name + '!')
}

greet = function(name) {
}
 */

(function() {
  var greet, rand, test,
    __slice = [].slice;

  greet = function(name) {
    name = name || "friend";
    return console.log("Hello " + name + "!");
  };

  greet("CoffeScripters");

  greet() + 10;

  greet = function(name) {
    name = name || "friend";
    return "Hello " + name + "!";
  };

  console.log(greet());

  greet = function(name) {
    if (name == null) {
      name = "friend";
    }
    return "Hello " + name + "!";
  };

  console.log(greet("Rafal"));

  test = function() {
    var x, y, z;
    x = arguments[0], y = arguments[1], z = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    console.log(x);
    console.log(y);
    return console.log(z);
  };

  test("one", "two", "three");

  console.log("=================");

  test("one", "two", "three", "four", "five");

  test.apply(null, ["one", "two", "three", "four", "five"]);

  (function() {
    return console.log("Hello");
  });

  (function() {
    return console.log("Hello");
  })();

  (function(message) {
    return console.log(message);
  })("Hello");

  rand = function(max, min) {
    if (max == null) {
      max = 10;
    }
    if (min == null) {
      min = 0;
    }
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

  console.log(rand());

  console.log(rand(100));

  console.log(rand(60, 50));

}).call(this);
