// Generated by CoffeeScript 1.7.1
(function() {
  var giveWork, greet, machine, name, person, person1, person2;

  name = "Rafal";

  if (name === "Rafal") {
    console.log(name);
  } else if (name === "Joe") {
    console("Hi " + name);
  } else {
    console.log("What's your name");
  }

  if (name === "Rafal") {
    console.log(name);
  } else if (name === "Joe") {
    console("Hi " + name);
  } else {
    console.log("What's your name");
  }

  if (name === "Rafal") {
    console.log(name);
  }

  if (name === "Rafal") {
    console.log;
  }

  name = "Rafal";

  machine = {
    running: false,
    turnOn: function() {
      return this.running = true;
    },
    tunrOff: function() {
      return this.running = false;
    }
  };

  if (!machine.running) {
    machine.turnOn();
  }

  if (!machine.running) {
    machine.turnOn();
  }

  console.log(machine.running);

  if (!machine.running) {
    machine.turnOn();
  } else {
    machine.turnOff();
  }

  person = {
    name: 'Rafal',
    job: 'Programmer'
  };

  giveWork = function(person) {
    switch (person.job) {
      case 'Programmer':
        return console.log("Here's your code work, " + person.name);
      case 'Designer':
        return console.log("Here's your design work, " + person.name);
      default:
        return console.log("Um, do you work here?");
    }
  };

  giveWork = function(person) {
    switch (person.job) {
      case 'Programmer':
        return console.log("Here's your code work, " + person.name);
      case 'Designer':
        return console.log("Here's your design work, " + person.name);
      default:
        return console.log("Um, do you work here?");
    }
  };

  giveWork(person);

  person1 = {
    name: "Rafal",
    relationship: "Friend"
  };

  person2 = {
    name: 'Jane',
    relationship: "Boss"
  };

  greet = function(person) {
    if (person.relationship === "Friend") {
      return console.log("Hi, " + person.name);
    } else if (person.relationship === "Boss") {
      return console.log("Hello, ma'am!");
    }
  };

  greet = function(person) {
    var msg;
    msg = person.relationship === "Friend" ? "Hi, " + person.name : person.relationship === "Boss" ? "Hello, ma'am!" : void 0;
    return console.log(msg);
  };

  greet = function(person) {
    return console.log(person.relationship === "Friend" ? "Hi, " + person.name : person.relationship === "Boss" ? "Hello, ma'am!" : void 0);
  };

  greet = function(person) {
    var msg;
    msg = (function() {
      switch (person.relationship) {
        case "Friend":
          return "Hi, " + person.name;
        case "Boss":
          return "Hello, ma'am!";
      }
    })();
    return console.log(msg);
  };

  greet(person1);

  greet(person2);

}).call(this);
